version: '3.8'

services:
  postgres-db:
    image: postgres
    container_name: postgres-db-marketplace
    environment:
      POSTGRES_DB: Marketplace
      POSTGRES_USER: adminDB
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    networks:
      - main

networks:
  main:
    driver: bridge

volumes:
  postgres_db_data: